### PR TITLE
fix: pickup default behavior of on_error.continue, lang, returnV1Comp…

### LINKED ISSUE #985: Add `defaults` key in config/default.yaml to give default values of keys used in workflow DSL
## The Problem 
Workflow task DSL has `on_error` key. Further `on_error` has the below structure:
```
on_error:
   continue: <true/false>
   response: <customizes repsonse>
```

By default, the framework sets continue to true if not specified. However, IMHO it should be false. 
There should be a way where we can control the default behavior at the `config` level.

- [x] Set `lang` for the default language in inline scripting
- [x] Set `on_error.continue` property to control the default behavior of on_error.
- [x] Set `returnV1Compatible` flag to make the com.gs.return behavior same as that of `v1` release.

## The Solution
Add `defaults` key in `config/default.yaml` which provides a way to specify the default values of the below keys.
```
defaults:
   lang: js #coffee
   on_error:
      continue: false
   returnV1Compatible: true/false
```

## How will we solve
Read default values of the above keys from `config.defaults` in the code. 

### Test case 1
Specify `defaults.lang: js` in `config/default.yaml`. Verify that the args in the below task are computed as `js`
```
  - id: return_result
    fn: com.gs.transform
    args:
      data: |
        <%
          const { page_number, page_size, ...rest } = inputs.body;
          return rest;
        %>
```

### Test case 2
Specify `defaults.on_error.continue: false` in `config/default.yaml`. Verify that `call_next` task is not executed.
```
  - id: call_findMany
    fn: com.gs.transform
    args: 
       success: false
    on_error:
      response:
        success: false
        data: <% outputs.call_findMany.data %>
  - id: call_next
    fn: com.gs.transform
    args: 
       key1: "value1"
```

### PR DESCRIPTION
**Pull request by gurjotkaur20**
Fixes #985

### CODE REVIEW

File: src/core/interfaces.ts [hunk 1]
```diff
@@ -437,7 +437,8 @@ export class GSFunction extends Function {
           ctx.childLogger.setBindings({ error });
         }
 
-        if (this.onError.continue === false) {
+        const onErrorContinue = this.onError.continue ?? ctx.config?.defaults?.on_error?.continue;
+        if (onErrorContinue === false) {
```
Comment (mastersilv3r) [inline src/core/interfaces.ts:441]: Should we not stop by default.. even if it is undefined?

File: src/core/utils.ts [hunk 2]
```diff
@@ -167,7 +167,7 @@ export function prepareScript(str: string, location: PlainObject): Function {
   let langs = (/<(.*?)%/).exec(str);
 
   //@ts-ignore
-  const lang = langs[1] || config.lang || 'js';
+  const lang = langs[1] || config.defaults?.lang || 'js';
```
Comment (mastersilv3r) [inline src/core/utils.ts:170]: Suggest to keep it backward compatible so that even by mistake if developer does not upgrade old projects, it continues to work

File: src/core/interfaces.ts (hunk 1 above)
Comment (gurjotkaur20) [reply src/core/interfaces.ts:441]: Done. Added 'false'.

File: src/core/utils.ts (hunk 2 above)
Comment (gurjotkaur20) [reply src/core/utils.ts]: Done
