### PR TITLE
fix: refactor caching methods

### LINKED ISSUE #737: V2: Caching in nodeJS V2 framework
Linked to PR #929 
Linked to Issue #1004  

### The problem
The caching doesn't work in V2, [as it used to work in V1](https://docs.godspeed.systems/v1/microservices/caching). Further, even in v1
- We are not able to setup a custom cache apart from Redis
- We can not use two caches in a project. 
- We can not set a custom cache in a particular caching instruction.
- We are not able to set expiry in milliseconds or leverage other Redis supported set options. Called [set.RedisOptions](https://redis.io/commands/set/) We should be able to leverage them atleast for Redis datasource

### The solution
- Developer should be able to read and return from cache if data is present there, before executing any task where `caching` instruction is set. 
- Data will be stored in form of `GSStatus` of the executed task. Both success and failure statuses can be stored and loaded.
- **Default cache** - You can cache task results for expensive computations or IO ops, by specifying a `GSCachingDatasource` instance in `caching` key in config/default.yaml. You can give the name of a `GSCachingDatasource` instance there. This will become the default cache for the entire service. 
- In a task, if we wants to override the default cache for the service and use custom cache, then you can add the `datasource` key in the `caching` tag of the task. `datasource` key helps override the default cache datasource for this task, set above.
-  `options` key takes RedisOptions. This replaces the `expires` timer in seconds from V1, which was actually [set.RedisOptions](https://redis.io/commands/set/) `EX`. Now developer gets all the Redis options if they use Redis datasource. Other caching datasources can support RedisOptions, and it is upto the developer to choose based on what (s)he needs.
```typescript
type RedisOptions = { //Visit set.RedisOptions.set page on the web and when documenting on our docs, add meaning of each option in documentation.
  EX? : number,
  PX? : number,
  EXAT?: number,
  NX?: boolean,
  XX?: boolean,
  KEEPTTL?: boolean,
  GET?: boolean
}
```
### Sample caching instruction at the task level
```yaml
# In Yaml Caching instruction is to be set parallel to the `{fn,id,summary,args}` instructions
  caching:
    before:
       datasource: in_mem_cache #Optional. the name of the datasource instance to use instead of default cache
       key: <Optional. Key name which is used to read from>
       invalidate: <Optional. Key name which we want to delete/remove from cache e.g. this feature can be used in CRUD types task. While delete operation, invalidate the cache of read or update task>
    after:
       datasource: in_mem_cache #Optional. the name of the datasource instance to use instead of default cache
       key: <Optional. Key name which is used to set in the cache after the task. dont set this if you dont want to write to cache after the task>
       invalidate: <Optional. Key name which we want to delete/remove from cache e.g. this feature can be used in CRUD types task. While delete operation, invalidate the cache of read or update task. >
       cache_on_failure: <Optional. true|false, whether you want to cache the failure result or not. By default, it is false>
       options: #Optional
          EX: 200 <timer in seconds, until the cached result is valid> #Can pass any of RedisOptions, if supported by the specific caching Datasource 
```
### How will we solve

1. Create the  `GSCacheAsDatasource`  interface extending `GSDataSource` as follows
```typescript
export abstract class GSCachingDataSource extends GSDataSource {

  //Redis options are available [here](https://redis.io/commands/set/) Client may or may not support all actions. RedisOptions is a superset based on what Redis supports
  public abstract set(key:string, val: any, options: RedisOptions): any; 

  public abstract get(key: string): any; //Return the value stored against the key

  public abstract del(key: string): any; //Delete the key
}
```
2. Just before any datasource fn is executed, check if it has a `caching` instruction and execute it as per the 'Sample Caching Instruction At Task Level' section listed above.

### How will we test
- Test with Redis `GSCachingDatasource` for sure. You can also test with an in-memory cache `GSCachingDatasource` (latter pasted here). You can also test with a combination of two `GSCachingDatasources`
```yaml
type: mem-cache #name of the in memory datasource type
```
### Create a mem-cache.ts in datasources/types
```typescript
import { GSCachingDataSource, GSContext, PlainObject} from "@godspeedsystems/core";

export default class MemCacheDs extends GSCachingDataSource {
    set(key: string, val: any, options: { EX?: number | undefined; PX?: number | undefined; EXAT?: number | undefined; NX?: boolean | undefined; XX?: boolean | undefined; KEEPTTL?: boolean | undefined; GET?: boolean | undefined; }) {
        console.log('set key %s %o', key, this.client)
        
        this.client[key] = val;
        console.log('after set %s %o', key, this.client)

    }
    get(key: string) {
        console.log('get %s %o', key, this.client)
        return this.client[key];
    }
    del(key: string) {
        console.log('del %s %o', key, this.client)

        delete this.client[key];
        console.log('after del %s %o', key, this.client)

    }
    protected async initClient(): Promise<PlainObject> {
        this.client = {};
        return this.client;
    }
    execute(ctx: GSContext, args: PlainObject): Promise<any> {
        throw new Error("Method not implemented.");
    }

}

``` 
- Create two events and two function handlers for each event by the name helloworld2 and helloworld3 respectively. 
```yaml
# Events
"http.get./helloworld2":
  fn: helloworld2
"http.get./helloworld3":
  fn: helloworld3

# Functions (Helloworld2 workflow)
id: helloworld2_workflow
tasks:
  - id: helloworld2_workflow_first_task
 
    fn: com.gs.transform
    args:
      name: helloworld2
    caching:
      key: xyz
      # datasource: memcache #This field should be definitely set if config/default.caching is not set. Else is optional
      # noRead: true #if this is set get(key) method will not be called for this task
      # noWrite: true #the result of this task will not be written, even if cache_on_failure is set to true. i.e. set() method will not be called
    

# Functions (Helloworld3 workflow)
id: helloworld3_workflow
tasks:
  - id: helloworld3_workflow_first_task
    caching:
      key: abc
      invalidate: xyz #helloworld2 key
      # noRead: true #if this is set get(key) method will not be called for this task
      # noWrite: true #the result of this task will not be written, even if cache_on_failure is set to true. i.e. set() method will not be called
      datasource: memcache #This field should be definitely set if config/default.caching is not set. Else is optional
    fn: com.gs.transform
    args:
      name: helloworld3
```
- Do note the console.log statements in the sample `mem-cache` `GSCachingDatasource` function. When you run helloworld2 and helloworld3 respectively you should see following log statements
```
//Hit helloworld2 first time
get xyz {}
set xyz {}
after set xyz { xyz: '{"success":true,"code":200,"data":{"name":"helloworld2"}}' }
//Hit helloworld2 second time or more
get xyz { xyz: '{"success":true,"code":200,"data":{"name":"helloworld2"}}' }
//Hit helloworld3 first time (after helloworld2 hits)
del xyz { xyz: '{"success":true,"code":200,"data":{"name":"helloworld2"}}' }
after del xyz {}
get abc {}
set abc {}
after set abc { abc: '{"success":false,"data":"failure data"}' }
//Hit helloworld3 second time
del xyz { abc: '{"success":false,"data":"failure data"}' }
after del xyz { abc: '{"success":false,"data":"failure data"}' }
get abc { abc: '{"success":false,"data":"failure data"}' }
```
- If a wrong datasource name is given in config/default or in tasks's caching instruction, the process must exit during runtime with similar error
```
 Could not find a valid datasource by the name memcache77 . Exiting
```
- You can play around with different options of the caching instruction. You can also set a global default cache, and use it in some function, and override in some another. All the combinations need to be tested via integration tests.

### PR DESCRIPTION
**Pull request by gurjotkaur20**
Fixes #737

### CODE REVIEW

File: src/core/caching.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+export async function preChecksAndInvalidateCache(ctx: GSContext, caching: GSFunction, taskValue: any) {
+    let cachingInstruction: PlainObject | null = null;
+    let cachingDs: GSCachingDataSource;
+    
+    cachingInstruction = await evaluateScript(ctx, caching, taskValue);
+    if (!cachingInstruction) {
+      logger.error('Error in evaluating cachingInstruction %o', caching);
+      throw new Error('Error in evaluating caching script');
+    }
+    const cachingDsName: string = cachingInstruction?.datasource || (config as any).caching;
```
Comment (mastersilv3r) [inline src/core/caching.ts:17]: ideally these two checks of valid caching datasource should happen at load time.

File: src/core/caching.ts [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+    };
+}
+
+export async function cacheBefore(cachingInstruction: PlainObject | null) {
+    let status;
+    const cachingDs: GSCachingDataSource = cachingInstruction?.cachingDs;
+
+    if (cachingInstruction?.key) {
+        // check in cache and return
+        status = await cachingDs.get(cachingInstruction?.key);
```
Comment (mastersilv3r) [inline src/core/caching.ts:44]: name of this function should be fetchFromCache

File: src/core/caching.ts [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+    }
+    return status;
+}
+
+export async function cacheAfter(ctx: GSContext, cachingInstruction: PlainObject | null, status: any) {
```
Comment (mastersilv3r) [inline src/core/caching.ts:49]: better name setInCache()

File: src/core/caching.ts [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+    const cachingDs: GSCachingDataSource = cachingInstruction?.cachingDs;
+
+    if (cachingInstruction?.key) {
+        if (status?.success || cachingInstruction.cache_on_failure) {
+            ctx.childLogger.debug('Storing task result in cache for %s and value %o', cachingInstruction.key, status);
```
Comment (mastersilv3r) [inline src/core/caching.ts:54]: here better to also add that this was a failure task (if it was so)

File: src/core/caching.ts (hunk 1 above)
Comment (gurjotkaur20) [reply src/core/caching.ts:33]: updated

File: src/core/caching.ts (hunk 2 above)
Comment (gurjotkaur20) [reply src/core/caching.ts:53]: done

File: src/core/caching.ts (hunk 3 above)
Comment (gurjotkaur20) [reply src/core/caching.ts]: done

File: src/core/caching.ts (hunk 4 above)
Comment (gurjotkaur20) [reply src/core/caching.ts]: Please check

File: src/core/caching.ts [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+        // check in cache and return
+        status = await cachingDs.get(cachingInstruction?.key);
+    }
+    return status;
+}
+
+export async function setInCache(ctx: GSContext, cachingInstruction: PlainObject | null, status: any) {
+    const cachingDs: GSCachingDataSource = cachingInstruction?.cachingDs;
+
+    if (cachingInstruction?.key) {
```
Comment (mastersilv3r) [inline src/core/caching.ts:62]: this check should be at the time of function calling for performance and also readability. Even if that is not done, the cachingDs variable initialisation should be within the if.
We should save unecessary compute cycles because this is a framework level computation will run on every task. 
 But this is a minor improvement. can leave it for now.

File: src/core/caching.ts [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+        logger.fatal(location, 'Exiting. Could not find a valid datasource by the name %s in the caching instruction %o', cachingDsName, caching);
+        process.exit(1);
+    }
+}
+
+export async function evaluateCachingInstAndInvalidates(ctx: GSContext, caching: GSFunction, taskValue: any) {
+    let cachingInstruction: PlainObject | null = null;   
+    cachingInstruction = await evaluateScript(ctx, caching, taskValue);
+    if (!cachingInstruction) {
+        ctx.childLogger.error('Error in evaluating cachingInstruction %o', caching);
```
Comment (mastersilv3r) [inline src/core/caching.ts:31]: have it been tested what happens here when you throw error? Does service handle it gracefully with 500?

**Comment by mastersilv3r** [comment]
Looks fine to merge.

**Review by mastersilv3r — APPROVED** [review]
